#
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

#
# Global Configuration
# -----------------------------------------------------------------------------
title: RYER THE CATCHER
email: ryerh@live.com
address: 中国，北京
description: H ♥︎ Z
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ryerh.com" # the base hostname & protocol for your site
# enforce_ssl: ryerh.com
twitter_username: ryerwong
github_username: ryerh
disqus_shorname: ryerh

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

#
# Global Configuration
# -----------------------------------------------------------------------------


#
# Serve Command Options
# -----------------------------------------------------------------------------
host: 0.0.0.0
port: 3004
