# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryer the catcher
email: ryerh@live.com
address: 中国，北京
description: H ♥︎ Z
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ryerh.com" # the base hostname & protocol for your site
enforce_ssl: ryerh.com
twitter_username: ryerwong
github_username:  ryerh

# Build settings
markdown: kramdown
