#
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: RYER THE CATCHER
timezone: Asia/Shanghai
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ryerh@live.com
address: 中国，北京
description: H ♥︎ Z
baseurl:
url: http://ryerh.com
twitter_username: ryerwong
github_username: ryerh
disqus_shorname: ryerh
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
host: 0.0.0.0
port: 3004
